<ul>
    <li><?php echo __(
            "Regular Expressions possible. %s",
            '<a class="ext-link-icon"href="http://support.proxiblue.com.au/kb/faq.php?id=9"
             target="_blank">&nbsp;</a>'
        ); ?></li>
    <li><?php echo __(
            "Dynamic Variables allowed. %s
 ", '<a class="ext-link-icon"href="http://support.proxiblue.com.au/kb/faq.php?id=10"
             target="_blank">&nbsp;</a>'
        ); ?></li>
</ul>
