<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend">RapNet</h4>
	    <div class="form-buttons"></div>
	</div>
	<div id="rapnet" class="fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
		        		<td class="label" colspan="6">
			        		<label><strong>RapNet DLS API:</strong></label>
		        		</td>
					</tr>
					<tr>
		        		<td class="label">
			        		<button onclick="setLocation('<?php echo$this->getUrl("idealAdmin/uploadtool/getRapnetList"); ?>')" class="scalable go" type="button" title="<?php echo $this->__("Get New RapNet List") ?>"><span><span><span><?php echo $this->__("Get New RapNet List") ?></span></span></span></button>
		        		</td>
		        		<td class="label">
			        		<button onclick="setLocation('<?php echo$this->getUrl("idealAdmin/uploadtool/updateRapnetDiamonds"); ?>')" class="scalable go" type="button" title="<?php echo $this->__("Update RapNet Diamonds") ?>"><span><span><span><?php echo $this->__("Update RapNet Diamonds") ?></span></span></span></button>
		        		</td>
		        		<td class="label">
			        		<button onclick="setLocation('<?php echo $this->getUrl("idealAdmin/uploadtool/deleteDiamonds",array('source'=>'rapnet')); ?>')" class="scalable delete" type="button" title="<?php echo $this->__("Delete RapNet Diamonds") ?>"><span><span><span><?php echo $this->__("Delete RapNet Diamonds") ?></span></span></span></button>
		        		</td>
		        		<td class="label">
							<button onclick="setLocation('<?php echo $this->getUrl("idealAdmin/uploadtool/downloadListRapnet"); ?>')" class="scalable go" type="button" title="<?php echo $this->__("Download RapNet CSV") ?>"><span><span><span><?php echo $this->__("Download RapNet CSV") ?></span></span></span></button>
		        		</td>
					</tr>
					
					<tr>
		        		<td class="label" colspan="6">&nbsp;</td>
					</tr>
					<tr>
		        		<td class="label" colspan="6">
			        		<label><strong>RapNet Instant Inventory API:</strong></label>
		        		</td>
					</tr>

					<tr>
		        		<td class="label">
			        		<button onclick="setLocation('<?php echo$this->getUrl("idealAdmin/uploadtool/getRapnetInstantInvList"); ?>')" class="scalable go" type="button" title="<?php echo $this->__("Get New Rapnet Instant Inv List") ?>"><span><span><span><?php echo $this->__("Get New Rapnet Instant Inv List") ?></span></span></span></button>
		        		</td>
		        		<td class="label">
			        		<button onclick="setLocation('<?php echo$this->getUrl("idealAdmin/uploadtool/updateRapnetInstantInvDiamonds"); ?>')" class="scalable go" type="button" title="<?php echo $this->__("Update Rapnet Instant Inv Diamonds") ?>"><span><span><span><?php echo $this->__("Update Rapnet Instant Inv Diamonds") ?></span></span></span></button>
		        		</td>
		        		<td class="label">
			        		<button onclick="setLocation('<?php echo $this->getUrl("idealAdmin/uploadtool/deleteDiamonds",array('source'=>'rapnet_inst')); ?>')" class="scalable delete" type="button" title="<?php echo $this->__("Delete Rapnet Instant Inv Diamonds") ?>"><span><span><span><?php echo $this->__("Delete Rapnet Instant Inv Diamonds") ?></span></span></span></button>
		        		</td>
		        		<td class="label">
							<button onclick="setLocation('<?php echo $this->getUrl("idealAdmin/uploadtool/downloadListRapnetInstant"); ?>')" class="scalable go" type="button" title="<?php echo $this->__("Download Rapnet Instant Inv CSV") ?>"><span><span><span><?php echo $this->__("Download Rapnet Instant Inv CSV") ?></span></span></span></button>
						
		        		</td>
					</tr>
				</tbody>
			</table>
	    </div>
	</div>
</div>
