<?php
    //import font settings
	echo $this->getLayout()->createBlock('core/template')->setTemplate('diamondsearch/diamondview-css.phtml')->toHtml();
?>
<?php if(Mage::getStoreConfig('diamondsearch/general_settings/enable_captcha')==1): ?>
<script type="text/javascript" src="<?php echo $this->getBaseUrl().'js/captch/jquery.plugin.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->getBaseUrl().'js/captch/jquery.realperson.js'; ?>"></script>
<link type="text/css" href="<?php echo $this->getBaseUrl().'js/captch/jquery.realperson.css'; ?>" rel="stylesheet" >
</link>
<script>
	jQuery(function() {jQuery('#defaultReal').realperson();});
</script>
<?php endif; ?>
<?php if(isset($_REQUEST['msg'])): ?>
<ul class="messages">
	<li class="<?php if(isset($_REQUEST['msg'])) echo $_REQUEST['msg']; ?>-msg">
		<?php if($_REQUEST['msg'] == 'success' ): ?>
		Your inquiry was submitted and will be responded to as soon as possible. Thank you.
		<?php elseif($_REQUEST['msg'] == 'error' ): ?>
		Unable to submit your request. Please, try again later
		<?php endif; ?>
	</li>
</ul>
<?php endif; ?>
<?php
$isHttps = false;
if (Mage::app()->getStore()->isFrontUrlSecure() && Mage::app()->getRequest()->isSecure()) 
	$isHttps = true;							
?>
<?php 
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
?>
<?php 
	//FOR DIAMOND SEARCH TOP CONTENT
	echo $this->getLayout()->createBlock('diamondsearch/diamondsearch')->setTemplate('diamondsearch/diamondview-top.phtml')->toHtml();
?>
<div class="container ds-container pb20">
	<div class="diamonddetail col-md-12">
		<div class="">&nbsp;</div>
		<div class="col-md-6 col-sm-12 col-xs-12 offset-xs-0">
			<?php
function sortByOrder($a, $b) {
    return $a['sortorder'] - $b['sortorder'];
}
function values($val)
{
if (trim($val)=="") $ret="---";
else $ret=$val;
return $ret;
}

function writeover($img,$x,$y,$txt)
{
$im = imagecreatefromjpeg($img);
$red = imagecolorallocate($im, 0xFF, 0x00, 0x00);
$black = imagecolorallocate($im, 0xFF, 0xFF, 0xFF);

// Path to ttf font file
$font_file = './Arialnb.ttf';

// Draw the text over
imagefttext($im, 10, 0, $x, $y, $black,$font_file, $txt);

//create the final wtermarked image - everytime overwritten 
imagepng($im,"images/shapes/complete_outline.png");
imagedestroy($im);
}

// Output image to the browser
//header('Content-Type: image/png'); 
//$text1="xxx \n yyy";
//writeover('images/shapes/round_out.jpg','3','15',$text1);
function tinycert($theimg)
{
if ($theimg != ''){
	
	$header_response = get_headers($theimg, 1);
	
	if(strpos($header_response[0], "404" ) !== false) {
		echo "<div align='center'>Report not available.</div>";
	}
	else { 
		echo"<div align='center'>";
		echo '<a rel="shadowbox" href="'.$theimg.'" ><img src="'.$theimg.'" width="100" heigh="120" /></a>';
		echo"</div><div align='center' style='margin-top:20px;'>"."<a rel='shadowbox' href='".$theimg."' >"."Report"."</a></div>";
	}
} else {
	echo "<div align='center'>"."Please E-mail us for Report"."</div>";
	}
}
function isValidCertUrl($url){
	if( is_null($url) || trim($url)=="")return false;
	
	$handle = curl_init($url);
	curl_setopt($handle,  CURLOPT_RETURNTRANSFER, TRUE);
	$response = curl_exec($handle);
	/* Check for 404 (file not found). */
	$httpCode = curl_getinfo($handle, CURLINFO_HTTP_CODE);
	if($httpCode == 404)return false;
	else return true;
	curl_close($handle);
}

?>
			<?php 

$id = $this->getRequest()->getParam('id');
$productid=$this->getRequest()->getParam('id');
$diamond = Mage::getModel("diamondsearch/diamondsearch")->load($this->getRequest()->getParam('id'))->getData();
if(empty($diamond)) echo "No diamond found.";
else{
//while($row=mysql_fetch_array($diamond)){
	$imgdir="images/certs/";
	$imgfile= trim($diamond['image']);
	$isValidCertUrl = isValidCertUrl($imgfile);
	//$imgfile="02752-01.jpg";
	//$theimg = $imgfile;

	$dim = $diamond['dimensions'];
	$findme   = '-';
	$dash_dim = strpos($dim, $findme);

	if ($dash_dim == true)
	{
		$dim_h_w_d = explode("x", $dim);

		$dim_h_w = trim($dim_h_w_d[0]);
		$dim_depth = trim($dim_h_w_d[1]);

		$remove_dash = explode("-", $dim_h_w);

		$height = trim($remove_dash[0]);
		$width = trim($remove_dash[1]);
	}
	else
	{
		$dim_h_w_d = explode("x", $dim);

		$height=trim($dim_h_w_d[0]);
		$width=trim($dim_h_w_d[1]);
		$dim_depth = trim($dim_h_w_d[2]);
	}

	//echo $theimg;
	$lotno=$diamond['lotno'];
	//diamonds_owner_mask
	$owner_mask_data = Mage::helper("diamondsearch")->getOwnerMaskArray();
	$owner = strtoupper($diamond['owner']);
	if(!empty($owner_mask_data))
		if(array_key_exists($diamond['owner'], $owner_mask_data))
			$owner = strtoupper($owner_mask_data[$diamond['owner']]);

	$shape=strtoupper($diamond['shape']);
	$carat=sprintf("%.2f",$diamond['carat']);
	$color=$diamond['color'];
	$clarity=$diamond['clarity'];	
	$cut=$diamond['cut'];		
	$depth=$diamond['depth'];
	$tabl=$diamond['tabl'];
	$polish=$diamond['polish'];
	$symmetry=$diamond['symmetry'];
	$fluorescence=$diamond['fluorescence'];
	$dimensions=$diamond['dimensions'];
	//$price="$".number_format($diamond['totalprice'], 2, '.', '');
	$price="$".number_format($diamond['totalprice']);
	$culet=$diamond['culet'];
	$girdle=$diamond['girdle'];
	$crown_ang=$diamond['crown'];
	$make=$diamond['make'];
	$crown_h=$diamond['crown_height'];
	$pavilion_h=$diamond['pavilion'];
	$owner_inhouse=Mage::getStoreConfig("diamondsearch/general_settings/inhouse_vendor");
	$depth_t=$dim_depth;
	$cert_number=$diamond['cert_number'];
	$certificate=$diamond['certificate'];
	$diamond_image = $diamond['diamond_image'];
	$diamond_video = $diamond['diamond_video'];
	$certificate_image = $diamond['image'];
	$ratio = $diamond['ratio'];
	$full_description = $diamond['full_description'];
	
	$image_or_video_link = trim($diamond['image_or_video_link']);
	$isSarineVideo = false;
	if($image_or_video_link && preg_match('/^<iframe /',$image_or_video_link)){
		preg_match('/src="([^"]+)"/', $image_or_video_link, $match);
		$image_or_video_link = $match[1];
	}
	$parse = parse_url($image_or_video_link);
	if(strtolower($parse["host"])=="api.sarine.com"){
		$isSarineVideo = true;
		$image_or_video_link = '<iframe width="100%" height="100%" frameborder="0" style="min-height:650px;" src="'.trim($diamond['image_or_video_link']).'" seamless="seamless"></iframe>';
	}
	
	$photo2=$diamond['photo2'];
	$photo3=$diamond['photo3'];
	$photo4=$diamond['photo4'];
	$photo5=$diamond['photo5'];
	$photo6=$diamond['photo6'];
	$photo7=$diamond['photo7'];
	$photo8=$diamond['photo8'];
	$photo9=$diamond['photo9'];

	$cfp_data = Mage::helper("diamondsearch")->getCallForPriceData();
	$cfpEanble = $cfp_data["is_cfp"];
	$cfpMessage = $cfp_data["cfp_msg"];
	$show_measurement_image = Mage::getStoreConfig("diamondsearch/general_settings/show_measurement_image");
	$image_text = Mage::getStoreConfig("diamondsearch/general_settings/image_text");
	$show_cut_if_its_n = Mage::getStoreConfig("diamondsearch/general_settings/show_cut_if_its_n");
	$diamond_shape_title = Mage::getStoreConfig("diamondsearch/general_settings/diamond_shape_title");
//}

	$disable_lab = false;
	if(Mage::getStoreConfig("diamondsearch/general_settings/disable_lab"))$disable_lab = true;

	$isMobile = Mage::helper("diamondsearch")->isMobile();
?>
			<?php if(!$isSarineVideo): ?>
			<div align="center" class="thumb_main" id="diam_img">
				<?php $dia_img = "";?>
				<?php if($diamond_image != ""): ?>
				<?php $diamond_response = get_headers($diamond_image, 1); ?>
				<?php if(strpos($diamond_response[0], "404" ) !== false): ?>
				<?php $dia_img = $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>
				<a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" id='colorboximage'  style="display: none;"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>"></a> <a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" target="_blank" class="<?php echo (!$isMobile) ? "MagicZoom" : "" ?>" rel="zoom-position:inner;zoom-fade: true"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic.jpg"); ?>" width="270" height="252"></a>
				<?php if($image_text):?>
				<p><?php echo $image_text; ?></p>
				<?php endif; ?>
				<?php else: ?>
				<?php if(Mage::getStoreConfig("diamondsearch/general_settings/sample_avilability")==1): ?>
				<?php $dia_img = $diamond_image; ?>
				<a href="<?php echo $diamond_image; ?>" id='colorboximage'  style="display: none;" > <img src="<?php echo $diamond_image; ?>"></a> <a href="<?php echo $diamond_image; ?>" class="<?php echo (!$isMobile) ? "MagicZoom" : "" ?>" target="_blank" rel="zoom-position:inner;zoom-fade: true" > <img src="<?php echo $diamond_image; ?>" width="270" height="auto" ></a>
				<p>actual diamond</p>
				<?php else : ?>
				<?php $dia_img = $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>
				<a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>"  id='colorboximage'  style="display: none;"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" ></a> <a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" target="_blank" class="<?php echo (!$isMobile) ? "MagicZoom" : "" ?>" rel="zoom-position:inner;zoom-fade: true"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic.jpg"); ?>" width="270" height="252"></a>
				<?php if($image_text):?>
				<p><?php echo $image_text; ?></p>
				<?php endif; ?>
				<?php endif; ?>
				<?php endif; ?>
				<?php else: ?>
				<?php $dia_img = $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>
				<a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>"  id='colorboximage'  style="display: none;"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" ></a> <a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" target="_blank" class="<?php echo (!$isMobile) ? "MagicZoom" : "" ?>" rel="zoom-position:inner;zoom-fade: true"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic.jpg"); ?>" width="270" height="252"></a>
				<?php if($image_text):?>
				<p><?php echo $image_text; ?></p>
				<?php endif; ?>
				<?php endif; ?>
			</div>
			<?php if($show_measurement_image==1 && $dimensions !=""): ?>
			<div align="center" class="thumb_main hidden" id="meas_img"> <img src="<?php echo $this->getUrl("diamondsearch/image/index",array("shp" => strtolower($shape),"dim" => $dimensions)); ?>" alt="dim meas" width="270" height="auto" /> </div>
			<?php endif; ?>
			<div align="center" class="thumb_main hidden" id="video_img">
				<?php $vdo_img = ""; ?>
				<?php if($diamond_video != ""): ?>
				<?php $vdo_response = get_headers($diamond_video, 1); ?>
				<?php if(strpos($vdo_response[0], "404" ) != true): ?>
				<?php $vdo_img = $diamond_video; ?>
				<iframe src="<?php echo $diamond_video ?>" height="400px" width="100%" frameborder="0"></iframe>
				<?php endif; ?>
				<?php endif; ?>
			</div>
			<div class="col-md-12 col-sm-12 col-xs-12 mt10 mb10 pt10 offset-xs-0" style="display: table;">
				<ul class="thumb_container pt5">
					<?php if($dia_img): ?>
					<li><a href="javascript:" thumb_main_id="diam_img"><img src="<?php echo $dia_img; ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($show_measurement_image==1 && $dimensions !=""): ?>
					<li><a href="javascript:" thumb_main_id="meas_img"><img src="<?php echo $this->getUrl("diamondsearch/image/index",array("shp" => strtolower($shape),"dim" => $dimensions)); ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($vdo_img): ?>
					<li><a href="javascript:" thumb_main_id="video_img"><img src="<?php echo $this->getSkinUrl("dsearch/image/play-vdo.png"); ?>" height="60"></a></li>
					<?php endif; ?>
					<?php //if($certificate_image != ""): ?>
					<?php //$cert_response = get_headers($certificate_image, 1); ?>
					<?php //if(strpos($cert_response[0], "404" ) != true): ?>
					<?php if(!$disable_lab): ?>
					<?php $cer_img = $certificate_image; ?>
					<li>
						<?php /* <a href="<?php echo $this->getUrl("diamondsearch/index/cert", array("id"=>$diamond['id'])); ?>" thumb_main_id="cert_img" class="cert-pdf" target="_blank">	 */ ?>
						<?php $cert_number=str_replace("*","",$cert_number);  ?>
						<?php if(strtoupper(trim($certificate))=='GIA'): ?>
							<?php if($isValidCertUrl): ?>
								<?php echo "<a thumb_main_id='none' href='".$imgfile."' target='_blank'>" ?>
							<?php else: ?>
								<?php echo "<a thumb_main_id='none' href='".($isHttps?'https':'http')."://www.gia.edu/report-check?reportno=" . $cert_number ."' target='_blank'>" ?>
							<?php endif; ?>
						<?php elseif(strtoupper(trim($certificate))=='IGI'):   ?>
							<?php if($isValidCertUrl): ?>
								<?php echo "<a thumb_main_id='none' href='".$imgfile."' target='_blank'>" ?>
							<?php else: ?>
								<?php echo "<a thumb_main_id='none' href='".($isHttps?'https':'http')."://www.igiworldwide.com/verify.php?r=" . $cert_number ."' target='_blank' >" ?>
							<?php endif; ?>
						<?php elseif(strtoupper(trim($certificate))=='EGLUSA' or strtoupper(trim($certificate))=='EGL USA'):   ?>
							<?php if($isValidCertUrl): ?>
								<?php echo "<a thumb_main_id='none' href='".$imgfile."' target='_blank'>" ?>
							<?php else: ?>
								<?php echo "<a thumb_main_id='none' target='_blank'  href='".($isHttps?'https':'http')."://www.eglusa.com/verify-a-report-results/?st_num=" . $cert_number . "'>" ?>
							<?php endif; ?>
						<?php elseif(strtoupper(trim($certificate))=='AGS'):   ?>
							<?php if($isValidCertUrl): ?>
								<?php echo "<a thumb_main_id='none' href='".$imgfile."' target='_blank'>" ?>
							<?php else: ?>
								<?php echo "<a thumb_main_id='none' href='".($isHttps?'https':'http')."://www.agslab.com/reportTypes/gdqrnc.php?StoneID=" .$cert_number."&Weight=". $carat ."&D=1'>"?>
							<?php endif; ?>
						<?php else: ?>
							<?php echo "<a thumb_main_id='none' href='#'>" ?>
						<?php endif; ?>
						<?php if(strtoupper(trim($certificate))=='GIA') :?>
						<img src="<?php echo $this->getSkinUrl("dsearch/image/gia-cert-icon.jpg"); ?>" height="60">
						<?php else:?>
						<img src="<?php echo $this->getSkinUrl("dsearch/image/cert-pdf.png"); ?>" height="60">
						<?php endif; ?>
						</a></li>
					<?php endif; ?>
					<?php //endif; ?>
					<?php /* elseif($owner = "jb_brothers"): ?>
					<?php $cert_response = get_headers('http://www.jbbrothers.com/Online/General/CertificateImage.aspx?PktCode='.$lotno, 1); ?>
					<?php if(strpos($cert_response[0], "404" ) != true): ?>
						<li><a href="<?php echo 'http://www.jbbrothers.com/Online/General/CertificateImage.aspx?PktCode='.$lotno; ?>" target="_blank" thumb_main_id="cert_img" class="cert-pdf"><img src="<?php echo $this->getSkinUrl("dsearch/image/cert-pdf.png"); ?>" height="60"></a></li>
					<?php endif; */?>
					<?php //endif; ?>
				</ul>
				<ul class='pt5 img additionaimage'>
					<?php if($photo2 && getimagesize($photo2) !== false ): ?>
					<li><a class="mz-thumb" href="<?php echo $photo2 ?>"><img src="<?php echo $photo2 ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($photo3 && getimagesize($photo3) !== false): ?>
					<li><a  class="mz-thumb" href="<?php echo $photo3 ?>"><img src="<?php echo $photo3 ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($photo4 && getimagesize($photo4) !== false): ?>
					<li><a  class="mz-thumb" href="<?php echo $photo4 ?>"><img src="<?php echo $photo4 ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($photo5 && getimagesize($photo5) !== false): ?>
					<li><a  class="mz-thumb" href="<?php echo $photo5 ?>"><img src="<?php echo $photo5 ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($photo6 && getimagesize($photo6) !== false): ?>
					<li><a  class="mz-thumb" href="<?php echo $photo6 ?>"><img src="<?php echo $photo6 ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($photo7 && getimagesize($photo7) !== false): ?>
					<li><a  class="mz-thumb" href="<?php echo $photo7 ?>"><img src="<?php echo $photo7 ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($photo8 && getimagesize($photo8) !== false): ?>
					<li><a  class="mz-thumb" href="<?php echo $photo8 ?>"><img src="<?php echo $photo8 ?>" height="60"></a></li>
					<?php endif; ?>
					<?php if($photo9 && getimagesize($photo9) !== false): ?>
					<li><a  class="mz-thumb" href="<?php echo $photo9 ?>"><img src="<?php echo $photo9 ?>" height="60"></a></li>
					<?php endif; ?>
				</ul>
			</div>
			<?php else: //ends isSarineVideo?>
			<div align="center"> <?php echo $image_or_video_link; ?> </div>
			<?php endif; ?>
			<?php if(!$isMobile): ?>
			<div class="diamond-details-type-lists">
				<?php if ($cut) : 
		//get Slider Configs
		$cutSliderConfig = unserialize(Mage::getStoreConfig("diamondsearch/slider_settings/cut_slider"));
		usort($cutSliderConfig, 'sortByOrder');
		$cutsArray = array();
		foreach ($cutSliderConfig as $_item):
			$cutsArray[strtoupper($_item["label"])] = array("code" => explode(",",strtoupper($_item["code"])), "text" => $_item["text"]);
		endforeach;
	?>
				<div class="col-md-12 mb50 offset-xs-0">
					<ul class="list-unstyled">
						<li class="active">CUT</li>
					</ul>
					<ul class="list-unstyled cut">
						<?php
			foreach($cutsArray as $k=>$v){
				$class = "";
				if(in_array($cut, $cutsArray[$k]["code"])) 
				{	
					$class = "active";
					$cutText = $cutsArray[$k]["text"];
				}
				echo '<li class="'.$class.'">'.$k.'</li>';
			}
		?>
					</ul>
					<?php if($cutText):?>
					<p><?php echo $cutText ?></p>
					<?php endif;?>
				</div>
				<?php endif; ?>
				<?php if ($clarity) :
		//get Slider Configs
		$claritySliderConfig = unserialize(Mage::getStoreConfig("diamondsearch/slider_settings/clarity_slider"));
		usort($claritySliderConfig, 'sortByOrder');
		$claritiesArray = array();
		foreach ($claritySliderConfig as $_item):
			 $claritiesArray[] = array("label" => strtoupper($_item["label"]), "text"=> $_item["text"]);
		endforeach;
	 ?>
				<div class="col-md-12 mb50 offset-xs-0">
					<ul class="list-unstyled">
						<li class="active">CLARITY</li>
					</ul>
					<ul class="list-unstyled clarity">
						<?php
		$clarityText = "";
		for($i=0;$i<count($claritiesArray);$i++)
		{
			echo "<li ".((strtoupper($clarity)==$claritiesArray[$i]["label"]) ? "class='active'" : "").">".$claritiesArray[$i]["label"]."</li>";
			$clarityText = strtoupper($clarity)==$claritiesArray[$i]["label"] ? $claritiesArray[$i]["text"] : $clarityText;
		}
		?>
					</ul>
					<?php if($clarityText):?>
					<p><?php echo $clarityText ?></p>
					<?php endif;?>
				</div>
				<?php endif; ?>
				<?php if ($color) : 
		//get Slider Configs
		//color slider
		$colorSliderConfig = unserialize(Mage::getStoreConfig("diamondsearch/slider_settings/color_slider"));
		usort($colorSliderConfig, 'sortByOrder');
		$colorsArray = array();
		foreach ($colorSliderConfig as $_item):
			 $colorsArray[] = array("label" => strtoupper($_item["label"]), "text"=> $_item["text"]);
		endforeach;
	?>
				<div class="col-md-12 mb50 offset-xs-0">
					<ul class="list-unstyled">
						<li class="active">COLOR</li>
					</ul>
					<ul class="list-unstyled color">
						<?php
		$colorText = "";
		for($i=0;$i<count($colorsArray);$i++)
		{
			if (strpos($colorsArray[$i]["label"],'-') !== false) { //check for range, eg. L-Z
				$clrs = explode("-", $colorsArray[$i]["label"]);
				$clrs = range($clrs[0], $clrs[1]);
				echo "<li ".((in_array(strtoupper($color), $clrs)) ? "class='active'" : "").">".$colorsArray[$i]["label"]."</li>";
				$colorText = in_array(strtoupper($color), $clrs) ? $colorsArray[$i]["text"] : $colorText;
			}
			else{
				echo "<li ".((strtoupper($color)==$colorsArray[$i]["label"]) ? "class='active'" : "").">".$colorsArray[$i]["label"]."</li>";
				$colorText = strtoupper($color)==$colorsArray[$i]["label"] ? $colorsArray[$i]["text"] : $colorText;
			}
		}
		?>
					</ul>
					<?php if($colorText):?>
					<p><?php echo $colorText ?></p>
					<?php endif;?>
				</div>
				<?php endif; ?>
			</div>
			<?php endif; ?>
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12 offset-xs-0">
			<div class="main_form_detail">
				<div class="left_crt">
					<table>
						<tr>
							<td><div class="bigmenulist">
									<div class="diamond_detail">
										<?=$carat;?>
										Carat </div>
									<div class="diamond_name">
										<?php 
										$convShape = ucfirst(strtolower(getSpecialAbbr($diamond['shape'])));
										echo str_replace("{{shape}}", $convShape, $diamond_shape_title);				
										?>
										<?php 
										/*ucfirst(getSpecialAbbr(strtolower($diamond['shape'])))?>
										Cut<?php echo (Mage::getStoreConfig("diamondsearch/general_settings/use_as_gemsearch"))?"":" Diamond" 
										*/
										?>
									</div>
									<div class="short_info">
										<?php 
                  if(($cut != "None" && $cut != "N" && $cut != "" && !($show_cut_if_its_n)) || ($cut != "None" && $cut != "N" && $cut != "" && $show_cut_if_its_n)) 
						{
							echo cutvalue($cut). " CUT | ";
						}
						elseif(($cut == "None" || $cut == "N" || $cut == "") && $show_cut_if_its_n){
								echo cutvalue($cut). " CUT | ";
						}
						elseif(($cut == "None" || $cut == "N" || $cut == "") && !($show_cut_if_its_n)){
								echo "";
						}
						else{
								echo cutvalue($cut). " CUT | ";
						}
						  if($color)
						  {
							echo $color. " COLOR | ";
						  }
						  if($clarity)
						  {
							echo $clarity. " CLARITY";
						  }
					?>
									</div>
								</div>
								<br />
								<div> <strong class="pageselected">
									<div class="diamond_price_detail">
										<?php
							if($cfpEanble && $cfpEanble == 1) {
								echo $cfpMessage;
							} else {
								echo $price;
							}
							?>
									</div>
									</strong>
									<?php if(!$cfpEanble && $cfpEanble != 1 && $diamond['bankwire_price'] && Mage::getStoreConfig("diamondsearch/general_settings/diamonds_show_bankwireprice")): ?>
									<div class="short_info bankwire_price"> <?php echo "<b>$" .number_format($diamond['bankwire_price']).'</b> when paying with bank wire';  ?> </div>
									<?php endif; ?>
								</div>
								<br />
								<?php 

			  if($full_description){
				  echo '<div class="diamond_short_desc">'.$full_description.'</div>';
			  }
              elseif($diamDesc = Mage::getStoreConfig("diamondsearch/general_settings/diamond_description")){
              	$diamDesc = str_replace("{{carat}}", $carat, $diamDesc);              	
				if((cutvalue($cut) != "" && cutvalue($cut) != "None" && cutvalue($cut) != "N"  && !($show_cut_if_its_n)) ||  (cutvalue($cut) != "" && cutvalue($cut) != "None" && cutvalue($cut) != "N"  && $show_cut_if_its_n)){
					$diamDesc = str_replace("{{cut}}", cutvalue($cut), $diamDesc);
				}
				elseif((cutvalue($cut) == "" || cutvalue($cut) == "None" && cutvalue($cut) == "N")  && $show_cut_if_its_n){
						$diamDesc = str_replace("{{cut}}", cutvalue($cut), $diamDesc);
					}
				elseif((cutvalue($cut) == "" || cutvalue($cut) == "None" && cutvalue($cut) == "N")  && !($show_cut_if_its_n)){
						$diamDesc = str_replace("{{cut}}", cutvalue($cut), $diamDesc);
						$diamDesc = str_replace("Cut,", "", $diamDesc);
					}
				else{
					$diamDesc = str_replace("{{cut}}", cutvalue($cut), $diamDesc);
				}
              	$diamDesc = str_replace("{{color}}", $color, $diamDesc);
              	$diamDesc = str_replace("{{clarity}}", $clarity, $diamDesc);
              	$diamDesc = str_replace("{{shape}}", strtoupper(getSpecialAbbr(strtolower($diamond['shape']))), $diamDesc);
              	$diamDesc = str_replace("{{certificate}}", $certificate, $diamDesc);
              	echo '<div class="diamond_short_desc">'.$diamDesc.'</div>';
			  }
              ?></td>
						</tr>
					</table>
				</div>
			</div>
			<?php if($image_or_video_link && !$isSarineVideo): ?>
				<a class="diamdetail_video" href="<?php echo $image_or_video_link ?>"><img class='btn btn-default' src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/dsearch/vedio_icon.png' style="padding: 0px;" title="click to show/hide video"></a>
			<?php endif; ?>
			<div class="diamond-details-type-lists all-details">
		<?php 
          $disable_addtocart =  Mage::getStoreConfig("diamondsearch/general_settings/diamondsview_addtocart_disabled_shapes");
          $disable_addtocart_arr = array_map('trim', explode(",", strtoupper($disable_addtocart)));
          $disable_addtocart_btn = false;
          if(in_array( $shape, $disable_addtocart_arr )) $disable_addtocart_btn = true;
        ?>
				<div class="col-cart <?php echo ($disable_addtocart_btn ? "cart-disabled" : "") ?>">
					<?php if(!$disable_addtocart_btn): ?>
					<div class="add_to_cart">
						<?php 
					try
					{ 
						$Url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'uploadtool/index/addtocart/id/'.values($productid);
						$Url1 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'uploadtool/index/addtowishlist/id/'.values($productid); 
					}
					catch (Exception $e) {
						$Url = '';
						$Url1 = '';
					}
				?>
						<?php if($cfpEanble == 0): ?>
						<a target="_parent" href="<?php echo $Url; ?>">ADD TO CART</a>
						<?php endif; ?>
					</div>
					<?php endif; ?>
					<div class="add_to_wishlist"> <a target="_parent" title="Add to Wishlist" href="<?php echo $Url1; ?>">ADD TO WISHLIST</a> </div>
					<div class="add_inquire"> <a target="_parent" onClick="jQuery('.col-inquiry').slideToggle('fast');" title="INQUIRE" href="javascript:">INQUIRE</a> </div>
				</div>
				<div class="col-inquiry" style="display:none;">
					<ul class="list-unstyled">
						<li class="active">INQUIRE</li>
					</ul>
					<ul class="list-unstyled cut">
						<div class="diamond_request_form">
							<?php if($customInquiry = Mage::getStoreConfig("diamondsearch/general_settings/diamondinquiry_customform")): 
					$customInquiryHtml = $processor->filter($customInquiry);
            		echo $customInquiryHtml;
			else : ?>
							<form action="<?php echo Mage::getUrl('uploadtool/index/requestPost'); ?>" method="post" id="frmRequestForInfo">
								<input type="hidden" value="<?php echo $lotno; ?>" name="stock_number" id="stock_number" />
								<?php if($cfpEanble && $cfpEanble == 1) {
				  		$price = $cfpMessage;
				  	}
				 ?>
								<input type="hidden" value="<?php echo $price; ?>" name="totalprice" id="totalprice" />
								<input type="hidden" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" name="current_url" />
								<div class="field">
									<label class="required" for="firstname"><em>*</em>NAME</label>
									<div class="input-box">
										<input type="text" value="" name="firstname" id="firstname" class="required-entry" />
									</div>
								</div>
								<div class="field">
									<label class="required" for="email"><em>*</em>EMAIL</label>
									<div class="input-box">
										<input type="text" value="" name="email" id="email" class="required-entry validate-email" />
									</div>
								</div>
								<div class="field">
									<label class="required" for="phone"><em>*</em>PHONE</label>
									<div class="input-box">
										<input type="text" value="" name="phone" id="phone" class="required-entry" />
									</div>
								</div>
								<div class="field">
									<label class="required" for="comments"><em>*</em>COMMENTS</label>
									<div class="input-box">
										<textarea rows="10" cols="20" name="comments" id="comments" class="required-entry"></textarea>
									</div>
								</div>
								<div class="buttons-set">
									<?php if(Mage::getStoreConfig('diamondsearch/general_settings/enable_captcha')==1): ?>
									<div class="input-box field">
										<input type="text" class="required-entry" id="defaultReal" name="defaultReal">
									</div>
									<?php endif; ?>
									<button type="submit" name="send_request" class="button"><span><span>Submit</span></span> </button>
								</div>
								<?php /* ?> <p class="required  requ_message" style='display: none'>*&nbsp;Required Information</p> <?php */ ?>
							</form>
							<script type="text/javascript">
                //<![CDATA[
                var frmRequestForInfo = new VarienForm('frmRequestForInfo', true);
                //]]>;
                </script>
							<?php endif; ?>
						</div>
					</ul>
				</div>
<?php
$attribute_position = unserialize(Mage::getStoreConfig("diamondsearch/attribute_position"));
usort($attribute_position, 'sortByOrder');
//echo "<pre>";print_r($attribute_position);echo "</pre>";
/*
foreach($attribute_position as $attrPos):
	if(isset($attrPos['avilability']) && $attrPos['avilability'] != 1 ) continue;
	$details[$attrPos['sortorder']]['DetailsCode'] = $attrPos['DetailsCode'];
	$details[$attrPos['sortorder']]['Label'] = $attrPos['Label'];
	$details[] = array("label" => $_item["label"], "sortorder" => $_item["sortorder"]);
endforeach;
*/
function msort($array, $key, $sort_flags = SORT_REGULAR, $order = SORT_ASC){
    if (is_array($array) && count($array) > 0) {
        if (!empty($key)) {
            $mapping = array();
            foreach ($array as $k => $v) {
                $sort_key = '';
                if (!is_array($key)) {
                    $sort_key = $v[$key];
                } else {
                    foreach ($key as $key_key) {
                        $sort_key .= $v[$key_key];
                    }
                }
                $mapping[$k] = $sort_key;
            }
			switch ($order) {
				case SORT_ASC:
				asort($mapping, $sort_flags);
				break;
				case SORT_DESC:
				arsort($mapping, $sort_flags);
				break;
			}

            $sorted = array();
            foreach ($mapping as $k => $v) {
                $sorted[] = $array[$k];
            }
            return $sorted;
        }
    }
    return $array;
}
$details = msort($attribute_position, array('sortorder'));

function fullform($value){
	$value = strtoupper($value);
	$arrayFF = array(
		"VG"  => "VERY GOOD",
		"G"   => "GOOD",
		"F"   => "FAIR",
		"I"   => "IDEAL",
	    "EX"  => "EXCELLENT",
		"N"  => "NONE",
	);
	if($arrayFF[$value]){return $arrayFF[$value];}else{return $value;}
}

function getCulet($value){
	$value = strtoupper($value);
	$arrayFF = array(
			"L" => " LARGE",
			"M" => " MEDIUM",
			"N" => "NONE",
			"S" => " SMALL",
	    	"SL"=> "SLIGHTLY LARGE",
			"VS"=> "VERY SMALL",
	);
	if($arrayFF[$value]){
		return $arrayFF[$value];
	}else{return $value;
	}
}

function getflourAbbr($value){
	$value = strtoupper($value);
	$arrayFF = array(
			"VS" => "VERY STRONG",
			"S" => "STRONG",
			"F" => "FAINT",
			"EX"=> "EXCELLENT",
			"N"=> "NONE",
			"M"=>"MEDIUM",
	);
	if($arrayFF[$value]){
		return $arrayFF[$value];
	}else{return $value;
	}
}

function girdleform($value){
	$value = strtoupper($value);
	$arrayFF = array (
		"M-VTK" =>  "Medium to Very Thick",
		"STK-TK" =>  "Slightly Thick to Thick",
		"M-M" =>  "Medium",
		"STK-VTK" =>  "Slightly Thick to Very Thick",
		"TN-TK" =>  "Thin to Thick",
	    "TK-ETK" =>  "Thick to Extremely Thick",
	    "VTN-STK" => "Very Thin to Slightly Thick",
	    "TK" =>  "Thick",
	    "M-STK" =>  "Medium to Slightly Thick",
	    "TN" =>  "Thin",
	    "M" =>  "Medium",
	    "M-STK" => "Medium to Slightly Thick",
	    "M-TK" => "Medium to Thick",
	    "TN-STK" => "Thin to Slightly Thick",
	    "M-TK" => "Medium to Thick",
	    "TN-M" => "Thin to Medium",
	    "TN-VTK" => "Thin to Very Thick",
	    "TK-VTK" => "Thick to Very Thick",
	    "VTN-TN" =>  "Very Thin to Thin",
	    "VTN-TK" => "Very Thin to Thick",
	    "TK-TK" => "Thick to Thick",
	    "ETN-STK" => "Extremely Thin to Slightly Thick",
	    "STK-ETK" => "Slightly Thick to Extremely Thick",
	    "VTK-ETK" => "Very Thick to Extremely Thick",
	    "SLIGHTLY THIN - SLIGHTLY THIN" => "Slightly Thin to Slightly Thin",
	    "SLIGHTLY THIN - SLIGHTLY THICK"=> "Slightly Thin to Slightly Thick",
	    "SLIGHTLY THIN - MEDIUM"=> "Slightly Thin to Medium",
	    "SLIGHTLY THICK - VERY THICK"=> "Slightly Thick to Very Thick",
	    "SLIGHTLY THICK - THIN"=> "Slightly Thick to Thin",
	    "SLIGHTLY THICK - THICK"=> "Slightly Thick to Thick",
	    "SLIGHTLY THICK - SLIGHTLY THICK"=> "Slightly Thick to Slightly Thick",
	    "SLIGHTLY THICK - MEDIUM"=> "Slightly Thick to Medium",
	    "SLIGHTLY THICK - EXTRA. THICK"=> "Slightly Thick to Extr. Thick",
	    "MEDIUM - VERY THICK"=> "Medium to Very Thick",
	    "MEDIUM - THIN"=>  "Medium - Thin",
	    "MEDIUM - THICK"=> "Medium - Thick",
	    "MEDIUM - SLIGHTLY THIN"=>  "Medium to Slightly Thin",
	    "MEDIUM - SLIGHTLY THICK"=>  "Medium - Slightly Thick", 
	    "MEDIUM - MEDIUM"=> "Medium",
	    "MEDIUM - EXTR. THIN"=> "Medium to Extremely Thin",
	    "MEDIUM - EXTR. THICK"=> "Medium to Extremely Thick",
	    "EXTR. THIN - VERY THIN"=> "Extremely Thin to Very Thin",
	    "EXTR. THIN - VERY THICK"=> "Extremely Thin to Very Thick",
	    "EXTR. THIN - THIN"=> "Extr. Thin to Thin",	
		   
	);  
	if($arrayFF[$value]){
		return $arrayFF[$value];
	}else{return $value;
	}
}
?>
				<div class="col-diamond-detail">
					<ul class="list-unstyled">
						<li class="active">DETAILS</li>
					</ul>
					<?php //echo "<pre>"; print_r($details); echo "</pre>"; ?>
					<?php foreach($details as $detail):?>
					<?php //echo $detail["DetailsCode"].' = inhouse';  ?>
					<?php  if($diamond[$detail["DetailsCode"]]=='' && $detail["DetailsCode"] != "inhouse" ) continue; 
					if($detail["avilability"] == "0") continue;
					?>
					
					<?php  if($detail["DetailsCode"]=='cut' && ($diamond[$detail["DetailsCode"]]=='' || $diamond[$detail["DetailsCode"]]=='None' || $diamond[$detail["DetailsCode"]]=='N') && !($show_cut_if_its_n)) continue;   ?>
					<ul class="list-unstyled">
						<li><?php echo $detail["Label"]?></li>
						<li DetailsCode="<?php echo $detail["DetailsCode"];?>">
							<?php //echo "<pre>"; print_r($diamond[]); 	 ?>
							<?php if($detail["DetailsCode"]=='carat'){ echo sprintf("%.2f",$diamond[$detail["DetailsCode"]]);}
						  
						  elseif($detail["DetailsCode"]=='dimensions'){
							 // echo str_replace('x', " x ", $diamond[$detail["DetailsCode"]])." mm";
						  	$mesurment= str_replace('x', " x ", $diamond[$detail["DetailsCode"]]);
						  	$mesurment= str_replace('-', " x ", $diamond[$detail["DetailsCode"]]);
						  	$mesurment= str_replace('|', " x ", $mesurment)." mm";
						  	echo $mesurment;
						  }
						  elseif($detail["DetailsCode"]=='inhouse'){
								if($owner_inhouse == $diamond["owner"])
								{
										if(Mage::getStoreConfig("diamondsearch/general_settings/inhousetextyes"))
										{
											echo Mage::getStoreConfig("diamondsearch/general_settings/inhousetextyes");
										}
										else
										{
											echo "Yes";
										}
								}
								elseif(Mage::getStoreConfig("diamondsearch/general_settings/inhousetext"))
								{ echo Mage::getStoreConfig("diamondsearch/general_settings/inhousetext");}
								else
								{ echo "Online Only";} 
						  }
						  elseif($detail["DetailsCode"]=='ratio' && ($diamond[$detail["DetailsCode"]] > 0)){
						  	echo sprintf("%.2f",$diamond[$detail["DetailsCode"]]);
						  }
						  elseif($detail["DetailsCode"]=='depth'){
						  		echo number_format(floatval($diamond[$detail["DetailsCode"]]),1)."%";
						  }
						  elseif($detail["DetailsCode"]=='tabl'){
						  		echo number_format(floatval($diamond[$detail["DetailsCode"]]),1)."%"; 
						  }
						  elseif($detail["DetailsCode"]=='color'){
						  	echo $diamond[$detail["DetailsCode"]];
						  }
						  elseif($detail["DetailsCode"]=='cash_price'){
						  		echo "$".number_format($diamond[$detail["DetailsCode"]]);
						  } 
						  elseif($detail["DetailsCode"]=='girdle'){
						  	echo strtoupper(girdleform($diamond[$detail["DetailsCode"]]));
						  }
						  elseif($detail["DetailsCode"]=='culet'){
						  	echo strtoupper(getCulet($diamond[$detail["DetailsCode"]]));
						  } 
						  elseif($detail["DetailsCode"]=='fluorescence'){
						  	echo strtoupper(getflourAbbr($diamond[$detail["DetailsCode"]]));
						  }
						  elseif($detail["DetailsCode"]=='cash_price'){
						  		echo "$".number_format($diamond[$detail["DetailsCode"]]);
						  }
						  elseif($detail["DetailsCode"]=='shape'){
						  	if($diamond[$detail["DetailsCode"]]==''){continue;}
						  	echo strtoupper(getSpecialAbbr(strtolower($diamond[$detail["DetailsCode"]])));
						  }
						   elseif($detail["DetailsCode"]=='owner'){
						  	if($diamond[$detail["DetailsCode"]]==''){continue;}
						  	echo strtoupper($owner);
						  }
						  else if($detail["DetailsCode"]=='cert_number' && strtoupper($diamond["certificate"])=='GIA' )
						  {
							if($isValidCertUrl):
								echo "<a class='gia_details' href='".$imgfile."' target='_blank' style='font-weight: bold;text-decoration:underline'>".strtoupper(trim($cert_number))."</a>";
							else:
								//$cert_number=$diamond[$detail["DetailsCode"]];
								$cert_number=str_replace("*","",$cert_number); 
								echo "<a class='gia_details' href='".($isHttps?'https':'http')."://www.gia.edu/report-check?reportno=" . $cert_number ."' target='_blank' style='font-weight: bold;text-decoration:underline'>".strtoupper(trim($cert_number))."</a>";
							endif;
						  }
						  else if($detail["DetailsCode"]=='cert_number' && strtoupper($diamond["certificate"])=='IGI' )
						  {
						  	//$cert_number=$diamond[$detail["DetailsCode"]];
						  	$cert_number=str_replace("*","",$cert_number); 
						  	echo "<a class='gia_details' href='".($isHttps?'https':'http')."://www.igiworldwide.com/verify.php?r=" . $cert_number ."' target='_blank' style='font-weight: bold;text-decoration:underline'>".strtoupper(trim($cert_number))."</a>";
						  }
						  elseif($detail["DetailsCode"]=='availability'){
						  	echo strtoupper(getAvail($diamond[$detail["DetailsCode"]]));
						  } 
						  else if($detail["DetailsCode"]=='cert_number' && (strtoupper($diamond["certificate"])=='EGLUSA' or strtoupper($diamond["certificate"])=='EGL USA') )
						  {
						  	$cert_number=str_replace("US","",$cert_number);
							echo "<a class='gia_details' style='font-weight: bold;text-decoration:underline' target='_blank'  href='".($isHttps?'https':'http')."://www.eglusa.com/verify-a-report-results/?st_num=" . $cert_number . "'>" . strtoupper(trim($cert_number)) ."</a>";
						  } 
						  else if($detail["DetailsCode"]=='cert_number' && strtoupper($diamond["certificate"])=='AGS')
						  {
						  	$cert_number=$diamond[$detail["DetailsCode"]];
						 	echo "<a class='gia_details' style='font-weight: bold;text-decoration:underline' target='_blank' href='".($isHttps?'https':'http')."://www.agslab.com/reportTypes/gdqrnc.php?StoneID=" .$cert_number."&Weight=". $carat ."&D=1'>". strtoupper(trim($cert_number)) ."</a>";
						  }
						  
						  else{
							  echo strtoupper(fullform($diamond[$detail["DetailsCode"]]));
							}?>
						</li>
					</ul>
					<?php endforeach;?>
				</div>
			</div>
		</div>
	</div>
	<div class="diamond_right"></div>
</div>
</div>
<script type="text/javascript">
jQuery(".thumb_container li a").click(function(){
	if(jQuery(this).hasClass("cert-pdf")){
		<?php if(!$isMobile): ?>
		jQuery(".cert-pdf").colorbox({iframe:true, width:"80%", height:"95%"});
		<?php endif; ?>
		return; 
	}
	if(jQuery(this).attr("thumb_main_id") == 'none') return;
	jQuery(".thumb_main,.meas_img").addClass("hidden");
	jQuery("#"+jQuery(this).attr("thumb_main_id")).removeClass("hidden");
}); 
</script>
<style>
.bigmenulist {
	text-transform: uppercase;
}
.diamond_detail {
	color: #000000;
    font-size: 20px;
}
.diamond_name {
    color: #000000;
    font-size: 30px;
}
.info_data li.active {
    background: none repeat scroll 0 0 #D2DAED;
    border: 1px solid;
    width: 100%;
}
.cut_info_data li {
    border: 1px solid;
    float: left;
    width: 25%;
}
.cut_info_data li.active {
    background: none repeat scroll 0 0 #D2DAED;
}
.nav .active > a {
    text-align: left;
}
.nav.info_result > li a {
    padding: 10px;
    text-align: center;
}
.diamond-details-type-lists {
    padding: 0;
}
.tabs-product-detail {
    color: #000000;
}
.diamond-details-type-lists .list-unstyled li {
    color: #000000;
    font-size: 17px;
    padding: 5px;
}
.col-md-12 .list-unstyled:nth-child(1) li {
    padding: 5px 20px;
    text-align: left;
    font-size: 25px;
}
.diamonddetail.col-md-12 {
    padding: 0;
}
.col-cart a {
  display: block;
  padding: 5px 0;
  text-align: center;
}
.all-details .list-unstyled > li:nth-child(1) {
    width: 50%;
}
.all-details .list-unstyled > li:nth-child(2) {
    background-color: #FFFFFF !important;
}
.bigmenulist .short_info {
    color: #000000;
    font-size: 20px;
}
.diamond_price_detail {
    color: #000000;
    font-size: 22px;
}
.diamond_short_desc {
    color: #000000;
    font-size: 15px;
}
.diamond-details-type-lists.all-details {
    margin-top: 30px !important;
    border: medium none !important;
}
.col-md-12 > p {
    color: #000000;
    font-size: 16px;
}
.diamond-details-type-lists .list-unstyled li.active {
    background-color: #D3DAED;
}
.diamond-details-type-lists .list-unstyled li {
    border: 1px solid #BDBFCC;
}
.list-unstyled.cut > li {
    width: 25%;
}
.list-unstyled.clarity > li {
    width: 12.5%;
}
.list-unstyled.color > li {
    width: 14.2857%;
}
.all-details .col-cart button {
    background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
    width: 100%;
}
.all-details .col-cart {
    display: inline-block;
    width: 100%;
}
.all-details .col-inquiry {
    margin-bottom: 15px;
}
.all-details .col-cart div {
    background: none repeat scroll 0 0 #D3DAED;
    display: inline-block;
    float: left;
    margin-bottom: 10px;
    margin-right: 2%;
    width: 32%;
}
.col-inquiry .diamond_request_form {
    padding: 10px 20px;
}
.diamond_request_form .field .button {
  background: none repeat scroll 0 0 #3B3B3B;
   padding: 2px 20px;
}
.diamond_request_form .field .button span {
    color: #FFFFFF;
    text-transform: none;
}
.all-details .col-cart div:last-child {
    margin: 0;
}
.col-diamond-detail {
    clear: both;
}
.diamond_request_form .field input, .diamond_request_form .field textarea {
    background: none repeat scroll 0 0 #E2E2E2;
    border: medium none;
    width: 100%;
    font-size: 20px;
}
/* SETTING DYNAMIC */
.list-unstyled.color > li{
<?php echo (!empty($colorsArray)) ? "width: ".(100/count($colorsArray))."%;" : "";
?>
}
.list-unstyled.clarity > li {
<?php echo (!empty($claritiesArray)) ? "width: ".(100/count($claritiesArray))."%;" : "";
?>
}
.list-unstyled.cut > li {
<?php echo (!empty($cutsArray)) ? "width: ".(100/count($cutsArray))."%;" : "";
?>
}
<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_textcolor")): ?>
.diamond-details-type-lists .list-unstyled li.active { color: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_textcolor") ?>}
<?php endif; ?>
<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_bgcolor")): ?>
.diamond-details-type-lists .list-unstyled li.active {background-color: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_bgcolor") ?>}
<?php endif; ?>
<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_textcolor")): ?>
.main-container .col-cart a {color: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_textcolor")." !important" ?>}
<?php endif; ?>
<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_bgcolor")): ?>
.all-details .col-cart div {background: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_bgcolor") ?>}
<?php endif; ?>
ul.thumb_container, ul.additionaimage {
  border-top: 1px solid #ddd;
  text-align: center;
}
ul.thumb_container li, ul.additionaimage li {
  display: inline-block;
}
ul.thumb_container li a, ul.additionaimage li a{display: block; margin: 3px; border: 1px solid #aaaaaa;}
@media(max-width:480px){
.list-unstyled.cut > li,.list-unstyled.clarity > li,.list-unstyled.color > li {
  float: left;
  width: 33.33%;
  line-height: 24px;
	}
.all-details .col-cart div{width:100%;}
}

#frmRequestForInfo .required:after {

	content: attr(data-before);
 }
.short_info.cash_price, .short_info.bankwire_price { font-size: 22px;}
</style>
<?php if(!$isMobile):?>
<script>
jQuery('#diam_img  #colorboximage').colorbox();
jQuery(document).ready(function(){
	jQuery("#diam_img a").click(function(){
  		jQuery( "#colorboximage img" ).colorbox({inline:true,open:true, href:"#colorboximage img" });
	});
	jQuery('#frmRequestForInfo .required').attr('data-before','');
	jQuery(".mz-thumb").colorbox({rel:'mz-thumb'});
});			 	 	
</script>
<?php endif;?>
<?php } ?>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery("#frmRequestForInfo .buttons-set button").click(function(){
		var error = 0;
		var firstname = jQuery("#frmRequestForInfo #firstname").val();
		//alert(firstname);
		/*if(firstname==''){alert("fname");error = 1;jQuery("#frmRequestForInfo label[for="firstname"] em").show();}
		if(error == 1){
			return false;	
		}*/		
	});
	<?php if($image_or_video_link && !$isSarineVideo): ?>
		jQuery(".diamdetail_video").colorbox({iframe:true, innerWidth:1024, innerHeight:768}); 
	<?php endif; ?>
	
});
</script>
<?php
function getSpecialAbbr($value)
{
	$arrayFF = array (
		"ascendancy_heart_arrows" =>  "Ascendancy Hearts & Arrows Round Cut",
		"platinum_select_round"=>"Platinum Select Round Brilliant",
		"the_solasfera_diamond"=>"Solasfera Diamond",
		"the_star_129"=>"Star129",
		"the_octavia_asscher"=>"SIGNATURE ASSCHER",
		"the_solasfera_princess"=>"The Solasfera Princess Cut",
		"ideal2_hearts_arrows"=>"Ideal2 Hearts & Arrows Radiant",
		"august_vintage_cushion"=>"August Vintage® Cushion",
		"platinum_select_vintage"=>"Platinum Select Vintage Cushion",   
		"platinum_select_princess"=>"Platinum select princess cut",
		"august_vintage_european"=>"August Vintage® European Cuts",
		"august_vintage_star"=>"August Vintage® Cushion",
		"platinum_select_modern"=>"Platinum Select Modern Cushion",
		"brellia_cushion_hearts"=>"SQUARE HEARTS & ARROWS",
		"vintage_cushion"=>"VINTAGE CUSHION",
		"rectangular_vintage_cushion"=>"RECTANGULAR VINTAGE CUSHION",
		) ;
	if($arrayFF[$value]){
		return $arrayFF[$value];
	}else{
		return $value;
	}	
}
function cutvalue($cut){
	$cut = strtoupper($cut);
	$cutslider = array(
		"VG"  => "VERY GOOD",
		"G"   => "GOOD",
		"F"   => "FAIR",
		"I"   => "IDEAL",
	    "EX"  => "EXCELLENT",
		"N"  => "NONE",
		"HA"  => "H&A",
		"BLAZING_ARROWS"  => "BLAZING ARROWS",
	);
	if($cutslider[$cut]){return $cutslider[$cut];}else{return $cut;}	
}
function getAvail($value)
{
	$value = strtoupper($value);
	$arrayFF = array (
		"G" =>  "Guaranteed",
		"M" =>  "On Memo", 
		);
	
	if($arrayFF[$value]){
		return $arrayFF[$value];
	}else{return $value;
	}
	 
}
?>
<?php 
	//FOR DIAMOND SEARCH BOTTOM CONTENT
	echo $this->getLayout()->createBlock('diamondsearch/diamondsearch')->setTemplate('diamondsearch/diamondview-bottom.phtml')->toHtml();
?>
