<ul class="messages"><li class="warning-msg">
        <ul>
            <li>
                <span>You are viewing a category with child categories.
                All child categories will automatically include the PARENT rules.
                You can disable this on child category.</span>
            </li>
        </ul>
    </li>
</ul>
<div class="entry-edit">
    <?php echo $this->getChildHtml('category_dyncatprod_rules'); ?>
</div>


