<?php if (Mage::getStoreConfig('dyncatprod/rebuild/delayed')): ?>
    <ul class="messages"><li class="warning-msg">
            <ul>
                <li>
                    <span>Delayed category building is enabled in configuration. The category dynamic products will rebuild via cron, after this category is saved.</span>
                </li>
            </ul>
        </li>
    </ul>
<?php endif; ?>
<?php if (Mage::getStoreConfig('dyncatprod/debug/enabled')): ?>
    <ul class="messages"><li class="warning-msg">
            <ul>
                <li>
                    <span>Debug Mode is enabled in configuration. This can slow down the build process. If debug is not required, disable in configuration to speed things up.</span>
                </li>
            </ul>
        </li>
    </ul>
<?php endif; ?>
<?php if (Mage::getStoreConfig('dyncatprod/global_rule/remove_manual_prod')): ?>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <span><strong>'Remove all manually assigned categories for dynamically assigned products' option</strong> is enabled in configuration.</span>
                </li>
            </ul>
        </li>
    </ul>
<?php endif; ?>
<?php if (Mage::getStoreConfig('dyncatprod/global_rule/remove_manual_cats')): ?>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <span><strong>'Remove all manually assigned products in a category' option </strong> is enabled in configuration.</span>
                </li>
            </ul>
        </li>
    </ul>
<?php endif; ?>
