<?php
 /**
 * GoMage Advanced Navigation Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2011 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 2.1
 * @since        Class available since Release 2.0
 */
?>
<?php 
 $category = Mage::registry('current_category');
if($category) {
    $currentcat = $category->getId();
}
?>
<?php if(isset($currentcat) && $currentcat == 106){ ?>

	<ol class="bridal <?php if($this->canShowCheckbox()):?>gan-list-checkbox<?php endif;?> <?php if($this->getFilterType()==GoMage_Navigation_Model_Layer::FILTER_TYPE_DEFAULT_INBLOCK):?>gan-inblock-list<?php endif;?>" <?php if($this->getFilterType()==GoMage_Navigation_Model_Layer::FILTER_TYPE_DEFAULT_INBLOCK):?>style="height:<?php echo $this->getInBlockHeight(); ?>px;"<?php endif;?>>
	
	<?php foreach ($this->getItems() as $_item): ?>				
	
		<li class="<?php echo $_item->getLabel(); ?>">
			<?php if ($_item->getCount() > 0 || $_item->getActive()): ?>
			<a <?php if($_item->getActive()):?> class="active" <?php endif;?> <?php if($this->ajaxEnabled()):?> onclick="setNavigationUrl('<?php echo urlencode($_item->getActive() ? $_item->getRemoveUrl(true) : $_item->getUrl(true)) ?>'); return false;" <?php endif;?> href="<?php echo ($_item->getActive() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
			<?php else: echo $_item->getLabel() ?>
			<?php endif; ?>
			
			<?php  if(!$_item->getActive()):?>
			<span class="count">(<?php echo $_item->getCount() ?>)</span>
			<?php  endif;?>
			
		</li>
	<?php endforeach ?>
	
	</ol>
	
<?php } else { ?>
							      
<ol class="<?php if($this->canShowCheckbox()):?>gan-list-checkbox<?php endif;?> <?php if($this->getFilterType()==GoMage_Navigation_Model_Layer::FILTER_TYPE_DEFAULT_INBLOCK):?>gan-inblock-list<?php endif;?>" <?php if($this->getFilterType()==GoMage_Navigation_Model_Layer::FILTER_TYPE_DEFAULT_INBLOCK):?>style="height:<?php echo $this->getInBlockHeight(); ?>px;"<?php endif;?>>
<?php foreach ($this->getItems() as $_item): ?>
	<?php //if($_item->getCount() <= 1) continue; ?>
    <li>
        <?php if ($_item->getCount() > 0 || $_item->getActive()): ?>
        <a <?php if($_item->getActive()):?> class="active" <?php endif;?> <?php if($this->ajaxEnabled()):?> onclick="setNavigationUrl('<?php echo urlencode($_item->getActive() ? $_item->getRemoveUrl(true) : $_item->getUrl(true)) ?>'); return false;" <?php endif;?> href="<?php echo ($_item->getActive() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
    	
		<?php  if(!$_item->getActive()):?>
        <span class="count">(<?php echo $_item->getCount() ?>)</span>
        <?php  endif;?>
		
    </li>
<?php endforeach ?>
</ol>

<?php } ?>

<!--

<script>
jQuery(document).ready(function(){
	
	jQuery("#advancednavigation-filter-content-product_type .bridal li").hide();
	jQuery("#advancednavigation-filter-content-product_type .bridal li.Engagement.Ring").show();
	
});
</script>
-->
