<?php if(isset($_REQUEST['msg'])): ?>
	<ul class="messages">
        <li class="<?php if(isset($_REQUEST['msg'])) echo $_REQUEST['msg']; ?>-msg">
          <?php if($_REQUEST['msg'] == 'success' ): ?>
          Your inquiry was submitted and will be responded to as soon as possible. Thank you.
          <?php elseif($_REQUEST['msg'] == 'error' ): ?>
          Unable to submit your request. Please, try again later
          <?php endif; ?>

        </li>

      </ul>



<?php endif; ?>



<link href='http://fonts.googleapis.com/css?family=Economica' rel='stylesheet' type='text/css'>



<div class="container ds-container pb20">



  <div class="diamonddetail col-md-12">



    <div class="">&nbsp;</div>



    <div class="col-md-6 col-sm-12 col-xs-12 offset-xs-0">



<?php



function sortByOrder($a, $b) {



    return $a['sortorder'] - $b['sortorder'];



}



function values($val)



{



if (trim($val)=="") $ret="---";



else $ret=$val;



return $ret;



}







function writeover($img,$x,$y,$txt)



{



$im = imagecreatefromjpeg($img);



$red = imagecolorallocate($im, 0xFF, 0x00, 0x00);



$black = imagecolorallocate($im, 0xFF, 0xFF, 0xFF);







// Path to ttf font file



$font_file = './Arialnb.ttf';







// Draw the text over



imagefttext($im, 10, 0, $x, $y, $black,$font_file, $txt);







//create the final wtermarked image - everytime overwritten 



imagepng($im,"images/shapes/complete_outline.png");



imagedestroy($im);



}







// Output image to the browser



//header('Content-Type: image/png'); 



//$text1="xxx \n yyy";



//writeover('images/shapes/round_out.jpg','3','15',$text1);



function tinycert($theimg)



{



if ($theimg != ''){



	



	$header_response = get_headers($theimg, 1);



	



	if(strpos($header_response[0], "404" ) !== false) {



		echo "<div align='center'>Certificate not available.</div>";



	}



	else { 



		echo"<div align='center'>";



		echo '<a rel="shadowbox" href="'.$theimg.'" ><img src="'.$theimg.'" width="100" heigh="120" /></a>';



		echo"</div><div align='center' style='margin-top:20px;'>"."<a rel='shadowbox' href='".$theimg."' >"."Certificate"."</a></div>";



	}



} else {



	echo "<div align='center'>"."Please E-mail us for Certificate"."</div>";



	}



}?>



      <?php 







$id = $this->getRequest()->getParam('id');



$diamond = Mage::getModel("diamondsearch/diamondsearch")->load($this->getRequest()->getParam('id'))->getData();



if(empty($diamond)) echo "No diamond found.";



else{



//while($row=mysql_fetch_array($diamond)){



	$imgdir="images/certs/";



	$imgfile= trim($diamond['image']);







	//$imgfile="02752-01.jpg";



	$theimg = $imgfile;







	$dim = $diamond['dimensions'];



	$findme   = '-';



	$dash_dim = strpos($dim, $findme);







	if ($dash_dim == true)



	{



		$dim_h_w_d = explode("x", $dim);







		$dim_h_w = trim($dim_h_w_d[0]);



		$dim_depth = trim($dim_h_w_d[1]);







		$remove_dash = explode("-", $dim_h_w);







		$height = trim($remove_dash[0]);



		$width = trim($remove_dash[1]);



	}



	else



	{



		$dim_h_w_d = explode("x", $dim);







		$height=trim($dim_h_w_d[0]);



		$width=trim($dim_h_w_d[1]);



		$dim_depth = trim($dim_h_w_d[2]);



	}







	//echo $theimg;



	$lotno=$diamond['lotno'];



	$owner=$diamond['owner'];



	$shape=strtoupper($diamond['shape']);



	$carat=sprintf("%.2f",$diamond['carat']);



	$color=$diamond['color'];



	$clarity=$diamond['clarity'];



	$cut=$diamond['cut'];



	$depth=$diamond['depth'];



	$tabl=$diamond['tabl'];



	$polish=$diamond['polish'];



	$symmetry=$diamond['symmetry'];



	$fluorescence=$diamond['fluorescence'];



	$dimensions=$diamond['dimensions'];



	//$price="$".number_format($diamond['totalprice'], 2, '.', '');



	$price="$".number_format($diamond['totalprice']);



	$culet=$diamond['culet'];



	$girdle=$diamond['girdle'];



	$crown_ang=$diamond['crown'];



	$make=$diamond['make'];



	$crown_h=$diamond['crown_height'];



	$pavilion_h=$diamond['pavilion'];



	$depth_t=$dim_depth;



	$cert_number=$diamond['cert_number'];



	$certificate=$diamond['certificate'];



	$diamond_image = $diamond['diamond_image'];



	$diamond_video = $diamond['diamond_video'];



	$certificate_image = $diamond['image'];


	$description= $diamond['full_description'];
	$diamond_polices= $diamond['diamond_polices'];
	



	$cfp_data = Mage::helper("diamondsearch")->getCallForPriceData();



	$cfpEanble = $cfp_data["is_cfp"];



	$cfpMessage = $cfp_data["cfp_msg"];



//}



	$isMobile = Mage::helper("diamondsearch")->isMobile();



?>



      



      <!-- <div id="counttotal" align="justify"></div>-->



      



      <div align="center" class="thumb_main" id="diam_img">



      <?php $dia_img = ""; ?>



        <?php if($diamond_image != ""): ?>



        <?php $diamond_response = get_headers($diamond_image, 1); ?>



        <?php if(strpos($diamond_response[0], "404" ) !== false): ?>



        	<?php $dia_img = $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>



        	<a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" id='colorboximage'  style="display: none;"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>"></a>



	        <a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" target="_blank" class="<?php echo (!$isMobile) ? "MagicZoom" : "" ?>" rel="zoom-position:inner;zoom-fade: true"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic.jpg"); ?>" width="270" height="252"></a>



	        <p>this is a sample image</p>



        <?php else: ?>



        	<?php $dia_img = $diamond_image; ?>



        	<a href="<?php echo $diamond_image; ?>" id='colorboximage'  style="display: none;" >



        		<img src="<?php echo $diamond_image; ?>"></a>



        	<a href="<?php echo $diamond_image; ?>" class="<?php echo (!$isMobile) ? "MagicZoom" : "" ?>" target="_blank" rel="zoom-position:inner;zoom-fade: true" >



        	<img src="<?php echo $diamond_image; ?>" width="270" height="auto" ></a>



        	<p>actual diamond</p>



        <?php endif; ?>



        <?php else: ?>



        	<?php $dia_img = $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>



        	 <a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>"  id='colorboximage'  style="display: none;"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" ></a>



	        <a href="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic_large.jpg"); ?>" target="_blank" class="<?php echo (!$isMobile) ? "MagicZoom" : "" ?>" rel="zoom-position:inner;zoom-fade: true"><img src="<?php echo $this->getSkinUrl("dsearch/shapes/".strtolower(trim($shape))."_pic.jpg"); ?>" width="270" height="252"></a>



	        <p>this is a sample image</p>



        <?php endif; ?>



      </div>

 



      <div align="center" class="thumb_main hidden" id="meas_img">



	  	<img src="<?php echo $this->getUrl("diamond-search/image/index",array("shp" => strtolower($shape),"dim" => $dimensions)); ?>" alt="dim meas" width="270" height="auto" />



      </div>



      



      <div align="center" class="thumb_main hidden" id="video_img">



      <?php $vdo_img = ""; ?>



        <?php if($diamond_video != ""): ?>



	        <?php $vdo_response = get_headers($diamond_video, 1); ?>



	        <?php if(strpos($vdo_response[0], "404" ) != true): ?>



	        	<?php $vdo_img = $diamond_video; ?>



	        	<iframe src="<?php echo $diamond_video ?>" height="400px" width="100%" frameborder="0"></iframe>



	        <?php endif; ?>



	    <?php endif; ?>



      </div>



      



      <div class="col-md-12 col-sm-12 col-xs-12 mt10 mb10 pt10 offset-xs-0" style="display: table;">

      	
    


	      <ul class="thumb_container pt5">



			<?php if($dia_img): ?>



	      		<li><a href="javascript:" thumb_main_id="diam_img"><img src="<?php echo $dia_img; ?>" height="60"></a></li>



	      	<?php endif; ?>



	      		<li><a href="javascript:" thumb_main_id="meas_img"><img src="<?php echo $this->getUrl("diamond-search/image/index",array("shp" => strtolower($shape),"dim" => $dimensions)); ?>" height="60"></a></li>



	      	<?php if($vdo_img): ?>



	      		<li><a href="javascript:" thumb_main_id="video_img"><img src="<?php echo $this->getSkinUrl("dsearch/image/play-vdo.png"); ?>" height="60"></a></li>



	      	<?php endif; ?>

			</ul>


		<ul class='thumb_container pt5 img'>
	      	<?php //if($certificate_image != ""): ?>



					<?php //$cert_response = get_headers($certificate_image, 1); ?>



					<?php //if(strpos($cert_response[0], "404" ) != true): ?>



						<?php $cer_img = $certificate_image; ?>



						<li><a href="<?php echo $this->getUrl("diamond-search/index/cert", array("id"=>$diamond['id'])); ?>" thumb_main_id="cert_img" class="cert-pdf" target="_blank">



                        <?php if(strtoupper(trim($certificate))=='GIA') :?>



                            <img src="<?php echo $this->getSkinUrl("dsearch/image/gia-cert-icon.jpg"); ?>" height="60">



                        <?php else:?>		



	                        <img src="<?php echo $this->getSkinUrl("dsearch/image/cert-pdf.png"); ?>" height="60">



                        <?php endif; ?>  



                        



                        </a></li>



					<?php //endif; ?>


 


			<?php //endif; ?>



	      </ul>


      </div>



      <div class="diamond-details-type-lists">



        <?php if ($cut) : 



			//get Slider Configs



			$cutSliderConfig = unserialize(Mage::getStoreConfig("diamondsearch/slider_settings/cut_slider"));



			usort($cutSliderConfig, 'sortByOrder');



			$cutsArray = array();



			foreach ($cutSliderConfig as $_item):



				$cutsArray[strtoupper($_item["label"])] = array("code" => explode(",",strtoupper($_item["code"])), "text" => $_item["text"]);



			endforeach;



		?>



        <div class="col-md-12 mb50 offset-xs-0">



          <ul class="list-unstyled">



            <li class="active">CUT</li>



          </ul>



          <ul class="list-unstyled cut">



            <?php



				foreach($cutsArray as $k=>$v){



					$class = "";



					if(in_array($cut, $cutsArray[$k]["code"])) 



					{	



						$class = "active";



						$cutText = $cutsArray[$k]["text"];



					}



					echo '<li class="'.$class.'">'.$k.'</li>';



				}



			?>



          </ul>



          <?php if($cutText):?><p><?php echo $cutText ?></p><?php endif;?>



        </div>



        <?php endif; ?>



        <?php if ($clarity) :



			//get Slider Configs



			$claritySliderConfig = unserialize(Mage::getStoreConfig("diamondsearch/slider_settings/clarity_slider"));



			usort($claritySliderConfig, 'sortByOrder');



			$claritiesArray = array();



			foreach ($claritySliderConfig as $_item):



				 $claritiesArray[] = array("label" => strtoupper($_item["label"]), "text"=> $_item["text"]);



			endforeach;



		 ?>



        <div class="col-md-12 mb50 offset-xs-0">



          <ul class="list-unstyled">



            <li class="active">CLARITY</li>



          </ul>



          <ul class="list-unstyled clarity">



            <?php



			$clarityText = "";



			for($i=0;$i<count($claritiesArray);$i++)



			{



				echo "<li ".((strtoupper($clarity)==$claritiesArray[$i]["label"]) ? "class='active'" : "").">".$claritiesArray[$i]["label"]."</li>";



				$clarityText = strtoupper($clarity)==$claritiesArray[$i]["label"] ? $claritiesArray[$i]["text"] : $clarityText;



			}



			?>



          </ul>



          <?php if($clarityText):?><p><?php echo $clarityText ?></p><?php endif;?>



        </div>



        <?php endif; ?>



        <?php if ($color) : 



			//get Slider Configs



			//color slider



			$colorSliderConfig = unserialize(Mage::getStoreConfig("diamondsearch/slider_settings/color_slider"));



			usort($colorSliderConfig, 'sortByOrder');



			$colorsArray = array();



			foreach ($colorSliderConfig as $_item):



				 $colorsArray[] = array("label" => strtoupper($_item["label"]), "text"=> $_item["text"]);



			endforeach;



		?>



        <div class="col-md-12 mb50 offset-xs-0">



          <ul class="list-unstyled">



            <li class="active">COLOR</li>



          </ul>



          <ul class="list-unstyled color">



            <?php



			$colorText = "";



			for($i=0;$i<count($colorsArray);$i++)



			{



				if (strpos($colorsArray[$i]["label"],'-') !== false) { //check for range, eg. L-Z



					$clrs = explode("-", $colorsArray[$i]["label"]);



					$clrs = range($clrs[0], $clrs[1]);



					echo "<li ".((in_array(strtoupper($color), $clrs)) ? "class='active'" : "").">".$colorsArray[$i]["label"]."</li>";



					$colorText = in_array(strtoupper($color), $clrs) ? $colorsArray[$i]["text"] : $colorText;



				}



				else{



					echo "<li ".((strtoupper($color)==$colorsArray[$i]["label"]) ? "class='active'" : "").">".$colorsArray[$i]["label"]."</li>";



					$colorText = strtoupper($color)==$colorsArray[$i]["label"] ? $colorsArray[$i]["text"] : $colorText;



				}



			}



			?>



          </ul>



          <?php if($colorText):?><p><?php echo $colorText ?></p><?php endif;?>



        </div>



        <?php endif; ?>



      </div>



    </div>



    <div class="col-md-6 col-sm-12 col-xs-12 offset-xs-0">



      <div class="main_form_detail">



        <div class="left_crt">



          <table>



            <tr>



            <td>



              <div class="bigmenulist">



                <div class="diamond_detail">



                  <?=$carat;?>



                  Carat </div>



                <div class="diamond_name">



                  <?=ucfirst(strtolower($shape))?>



                  Cut Diamond </div>



                <div class="short_info">



                  <?php if($cut) 



						  {



							echo $cut. " CUT | ";



						  }



						  if($color)



						  {



							echo $color. " COLOR | ";



						  }



						  if($clarity)



						  {



							echo $clarity. " CLARITY";



						  }



					?>



                </div>



              </div>



              <br />



              <div><strong class="pageselected">


       
                <div class="diamond_price_detail">



                  <?php



							if($cfpEanble && $cfpEanble == 1) {



						  		echo $cfpMessage;



						  	} else {



							  	echo $price;



						  	}



							?>



                </div>



                </strong> </div>

			 
			
		 
 
           
			  <br /> 	

 



              <?php 



function cutvalue($cut){

	$cutslider = array(

		"VG"  => "Very Good",

		"G"   => "Good",

		"F"   => "Fair",

		"I"   => "Ideal",

	    "EX"  => "Excellent",

		"N"  => "None",

	);

	if($cutslider[$cut]){return $cutslider[$cut];}else{return $cut;}	

}



              if($diamDesc = Mage::getStoreConfig("diamondsearch/general_settings/diamond_description")){

              	$diamDesc = str_replace("{{carat}}", $carat, $diamDesc);

              	$diamDesc = str_replace("{{cut}}", cutvalue($cut), $diamDesc);

              	$diamDesc = str_replace("{{color}}", $color, $diamDesc);

              	$diamDesc = str_replace("{{clarity}}", $clarity, $diamDesc);

              	$diamDesc = str_replace("{{shape}}", strtoupper($shape), $diamDesc);

              	$diamDesc = str_replace("{{certificate}}", $certificate, $diamDesc);

              	echo '<div class="diamond_short_desc">'.$diamDesc.'</div>';

              }

              ?>

                </td>



            </tr>



          </table>



        </div>



      </div>
				<div id='gemAdvisor' style="display: none">
  					<iframe width='200px'  src="http://www.w3schools.com"></iframe>
  				</div>
           <div class='diamond_details'>
          		<ul class='tabs'>
			    <li><a href='#tab1'>FULL DESCRIPTION</a></li>
			    <li><a href='#tab2'>DIAMOND POLICES</a></li>
			    <li><a href='#tab3'>ADDITIONAL INFORMATION</a></li>
			  </ul>
				  <div id='tab1'>
			  		<?php echo $diamDesc?>
			  			<br>
				     <?= $description;?>
				      
				  </div>
				  <div id='tab2'>
				    <?=$diamond_polices ?>
				  </div>
				  <div id='tab3'>
				    	<ul class="list-dimond_Detail">
							<li>CARAT WEIGHT:</li>
							<li> <?=values($carat);?> </li>	 
						</ul> 
						<ul class="list-dimond_Detail">
							<li>Shape:</li>
							<li><?=values($shape);?></li>
						</ul>
						<ul class="list-dimond_Detail">
							<li>Color:</li>
							<li><?= $color?></li>	 
						</ul>
						<ul class="list-dimond_Detail">
							<li>Clarity:</li>
							<li><?= $clarity?></li>	 
						</ul>
						<ul class="list-dimond_Detail">
							<li>GIA Cut Grade:</li>
							<li><?= $cut?></li>	 
						</ul>
						<ul class="list-dimond_Detail">
							<li>AGS Light Performance:</li>
							<li><?= ''?></li>	 
						</ul>
						<ul class="list-dimond_Detail">
							<li>Optical Symmetry</li>
							<li><?= $symmetry?></li>	 
						</ul>
						<ul class="list-dimond_Detail">
							<li>Polish:</li>
							<li><?= values($polish)?></li>	 
						</ul>
				  </div>
          </div>


      <div class="diamond-details-type-lists all-details">



        <div class="col-cart">

	 

          <div class="add_to_wishlist">



            <a target="_parent" title="Add to Wishlist" href="#">Add to Wishlist</a>



          </div>

     


          <div class="add_inquire">



          	<a target="_parent" onClick="jQuery('.col-inquiry').slideToggle('fast');" title="INQUIRE" href="javascript:">INQUIRE</a>



          </div>



        </div>



        <div class="col-inquiry" style="display:none;">



          <ul class="list-unstyled">



            <li class="active">INQUIRE</li>



          </ul>



          <ul class="list-unstyled cut">



            <div class="diamond_request_form">



              <form action="<?php echo Mage::getUrl('uploadtool/index/requestPost'); ?>" method="post" id="frmRequestForInfo">



                <input type="hidden" value="<?php echo $lotno; ?>" name="stock_number" id="stock_number" />



                <?php if($cfpEanble && $cfpEanble == 1) {



				  		$price = $cfpMessage;



				  	}



				 ?>



                <input type="hidden" value="<?php echo $price; ?>" name="totalprice" id="totalprice" />



                <input type="hidden" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" name="current_url" />



                <div class="field">



                <label class="required" for="firstname"><em>*</em>NAME</label>



                  <div class="input-box">



                    <input type="text" value="" name="firstname" id="firstname" class="required-entry" />



                  </div>



                </div>


 



                <div class="field">



                  <label class="required" for="email"><em>*</em>EMAIL</label>



                  <div class="input-box">



                    <input type="text" value="" name="email" id="email" class="required-entry" />



                  </div>



                </div>



                <div class="field">



                <label class="required" for="phone"><em>*</em>PHONE</label>



                  <div class="input-box">



                    <input type="text" value="" name="phone" id="phone" class="required-entry" />



                  </div>



                </div>



                <div class="field">



                	<label class="required" for="comments"><em>*</em>COMMENTS</label>



                  <div class="input-box">

 
                    <textarea rows="10" cols="20" name="comments" id="comments" class="required-entry"></textarea>
 
                  </div>
 
                </div>
 
                <div class="buttons-set">
                  <button type="submit" name="send_request" class="button"><span><span>Submit</span></span> </button>
                </div>
                <p class="required  requ_message" style='display: none'>*&nbsp;Required Information</p>
              </form>



              <script type="text/javascript">



					//<![CDATA[



						var frmRequestForInfo = new VarienForm('frmRequestForInfo', true);

 
					//]]>;



				</script> 



            </div>



          </ul>



        </div>

        <div class='certificate_avilability'>
       
        	<div class='certificate'>
        		<div class='cer_image'>
        			<img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>cert_images/GOG_DiamondDetails_34.jpg'/>
        		</div>
        		<div class='certificate_link'>
        		  <?php /* <a href='http://www.gia.edu/cs/Satellite?reportno=<?php echo $cert_number ?>&c=Page&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&cid=1355954554547&encryptedString=15BAEAB9D18DC8B6FF49E44006911'>VIEW GIA CERTIFICATE</a>*/ ?>

        		  <a href='#' class='iframe'>VIEW GIA CERTIFICATE</a>
        		</div>	
        	</div>
           
        	<div class='certificate'>
        		<div class='cer_image'>
        			<img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>cert_images/GOG_DiamondDetails_38.jpg'/>
        		</div>
        		<div class='certificate_links'>
        			<a href='#' class='iframe'>VIEW AGS CERTIFICATE</a>
        		</div>	
        	</div>
        	<div class='certificate'>
        		<div class='cer_image'>
        			<img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>cert_images/GOG_DiamondDetails_42.jpg'/>
        		</div>
        		<div class='certificate_links'>
        			<a class='iframe' href='#'>VIEW GIA CERTIFICATE</a>
        		</div>	
        	</div>
        	<div class='certificate fourth'>
        		<div class='cer_image'>
        			<img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>cert_images/GOG_DiamondDetails_46.jpg'/>
        		</div>
        		<div class='certificate_link'>
        			<a class='iframe' href='#'>VIEW HELIUM REPORT</a>
        		</div>	
        	</div>
        	<div class='certificate fifth'>  
        		<div class='cer_image'>
        			<img class='iframe' src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>cert_images/GOG_DiamondDetails_50.jpg'/>
        		</div>
        		<div class='certificate_link'>    
        			<a href='#' class='iframe'>VIEW GEM ADVISOR <br/>VIRTUAL MODEL</a>
        		</div>	
        	</div>
        </div>

      
      </div>



    </div>



  </div>

  
	

  <div class="diamond_right"></div>



</div>



</div>



<script type="text/javascript">
	jQuery(".thumb_container li a").click(function(){
		if(jQuery(this).hasClass("cert-pdf")){
			<?php if(!$isMobile): ?>
			jQuery(".cert-pdf").colorbox({iframe:true, width:"80%", height:"95%"});
			<?php endif; ?>
			return; 
		}
		jQuery(".thumb_main").addClass("hidden");
		jQuery("#"+jQuery(this).attr("thumb_main_id")).removeClass("hidden");
	  //	jQuery('.diamond_request_form .required:after').attr('content','none');
	});
</script>
<style>
.bigmenulist {text-transform: uppercase;}
.diamond_detail {color: #000000;font-size: 20px;font-family: economica;}
.diamond_name {color: #000000;font-size: 30px;font-weight: bold;font-family: economica;}
.info_data li.active {background: none repeat scroll 0 0 #D2DAED;border: 1px solid;width: 100%;}
.cut_info_data li {border: 1px solid;float: left;width: 25%;}
.cut_info_data li.active {background: none repeat scroll 0 0 #D2DAED;}
.nav .active > a {text-align: left;}
.nav.info_result > li a {padding: 10px;text-align: center;}
.diamond-details-type-lists {padding: 0;}
.tabs-product-detail {color: #000000;



}



.diamond-details-type-lists .list-unstyled li {



    color: #000000;



    font-size: 17px;



    padding: 5px;



}



.col-md-12 .list-unstyled:nth-child(1) li {



    padding: 5px 20px;



    text-align: left;



    font-size: 25px;



}



.diamonddetail.col-md-12 {



    padding: 0;



}



.col-cart a {



  display: block;



  padding: 5px 0;



  text-align: center;



}



.all-details .list-unstyled > li:nth-child(1) {



    width: 50%;



}



.all-details .list-unstyled > li:nth-child(2) {



    background-color: #FFFFFF !important;



}



.bigmenulist .short_info {



    color: #000000;



    font-family: economica;



    font-size: 20px;



}



.diamond_price_detail {



    color: #000000;



    font-size: 22px;



    font-family: economica;



}



.diamond_short_desc {



    color: #000000;



    font-size: 15px;



    font-family: economica;



}



.diamond-details-type-lists.all-details {



    margin-top: 30px !important;



    border: medium none !important;



}



.col-md-12 > p {



    color: #000000;



    font-family: economica;



    font-size: 16px;



}



.diamond-details-type-lists .list-unstyled li.active,.tabs .active {



    background-color: #D3DAED;



}



.diamond-details-type-lists .list-unstyled li {



    border: 1px solid #BDBFCC;



}



.list-unstyled.cut > li {



    width: 25%;



}



.list-unstyled.clarity > li {



    width: 12.5%;



}



.list-unstyled.color > li {



    width: 14.2857%;



}



.all-details .col-cart button {



    background: none repeat scroll 0 0 rgba(0, 0, 0, 0);



    width: 100%;



}



.all-details .col-cart {



    display: inline-block;



    width: 100%;



}



.all-details .col-inquiry {



    margin-bottom: 15px;



}



.all-details .col-cart div {



    background: none repeat scroll 0 0 #D3DAED;



    display: inline-block;



    



    margin-bottom: 10px;



    margin-right: 2%;



    width: 32%;



}



.col-inquiry .diamond_request_form {



    padding: 10px 20px;



}



.diamond_request_form .field .button {



  background: none repeat scroll 0 0 #3B3B3B;



   padding: 2px 20px;



}



.diamond_request_form .field .button span {



    color: #FFFFFF;



    text-transform: none;



}



.all-details .col-cart div:last-child {



    margin: 0;



}



.col-diamond-detail {



    clear: both;



}



.diamond_request_form .field input, .diamond_request_form .field textarea {



    background: none repeat scroll 0 0 #E2E2E2;



    border: medium none;



    width: 100%;



    font-size: 20px;



}



/* SETTING DYNAMIC */



.list-unstyled.color > li{



<?php echo (!empty($colorsArray)) ? "width: ".(100/count($colorsArray))."%;" : "";



?>



}



.list-unstyled.clarity > li {



<?php echo (!empty($claritiesArray)) ? "width: ".(100/count($claritiesArray))."%;" : "";



?>



}



.list-unstyled.cut > li {



<?php echo (!empty($cutsArray)) ? "width: ".(100/count($cutsArray))."%;" : "";



?>



}



<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_textcolor")): ?>



.diamond-details-type-lists .list-unstyled li.active,.tabs .active { color: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_textcolor") ?> !important }



<?php endif; ?>



<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_bgcolor")): ?>



.diamond-details-type-lists .list-unstyled li.active,.tabs .active {background-color: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_table_bgcolor") ?>}
<?php endif; ?>
<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_textcolor")): ?>
.main-container .col-cart a {color: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_textcolor")." !important" ?>}
<?php endif; ?>
<?php if(Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_bgcolor")): ?>
.all-details .col-cart div {background: <?php echo Mage::getStoreConfig("diamondsearch/design_settings/viewpage_button_bgcolor") ?>}
<?php endif; ?>
ul.thumb_container {border-top: 1px solid #ddd;/*text-align: center; */}
ul.thumb_container li {display: inline-block;}
ul.thumb_container li a{display: block; margin: 3px; border: 1px solid #aaaaaa;}
@media(max-width:480px){
.list-unstyled.cut > li,
.list-unstyled.clarity > li,.list-unstyled.color > li {float: left;width: 33.33%;line-height: 24px;}
.all-details .col-cart div{width:100%;}
}
#frmRequestForInfo .required:after {content: attr(data-before);}
#frmRequestForInfo label em{margin-right:5px;}
</style>
<?php if(!$isMobile):?>
<script>
jQuery('#diam_img  #colorboximage').colorbox();
jQuery(document).ready(function(){
	jQuery("#diam_img a").click(function(){
  		jQuery( "#colorboximage img" ).colorbox({inline:true,open:true, href:"#colorboximage img" });
	});
	jQuery('#frmRequestForInfo .required').attr('data-before','');

	
		jQuery(".iframe").colorbox({iframe:true, width:"80%", height:"80%"});
	
	
});			 	 	
</script>
<?php endif;?>
<?php } ?>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery("#frmRequestForInfo .buttons-set button").click(function(){
		var error = 0;
		var firstname = jQuery("#frmRequestForInfo #firstname").val();
		if(firstname==''){error = 1;jQuery("#frmRequestForInfo label[for='firstname'] em").show();}
		
		var email = jQuery("#frmRequestForInfo #email").val();
		if(email==''){error = 1;jQuery("#frmRequestForInfo label[for='email'] em").show();}
		
		var phone = jQuery("#frmRequestForInfo #phone").val();
		if(phone==''){error = 1;jQuery("#frmRequestForInfo label[for='phone'] em").show();}
		
		var comments = jQuery("#frmRequestForInfo #comments").val();
		if(comments==''){error = 1;jQuery("#frmRequestForInfo label[for='comments'] em").show();}
		
		if(error == 1){
			jQuery("#frmRequestForInfo .requ_message").show();
			return false;	
		}
	});
});
</script>

<style>
	/*
	.diamondsearch-index-view .container {
  		max-width: 948px;
	} */
	.certificate >div {
	  width: 50%;
	  float: left;
	  text-align: center;
	}
	
	.cer_image > img {
 	 margin: 0 auto;
	}
	
	.certificate {
	/*  border-bottom: 2px solid; */
	  border-top: 2px solid;
	  display: table;
	  width: 100%;
	  border-color: #eee;
	  padding-bottom: 2%;
	  padding-top: 2%;
	  margin-bottom: 2%;
	}
	
	 

	.certificate a {
	  border: 1px solid;
	  color: #000 !important;
	  margin-top: 5px !important;
	  padding: 6px;
	  display: block;
	}
	
	.tabs > li a {
	  /*color: #000 !important; */
	  display: block;
	  padding: 5px 9% 5px 8%;
	  width: 100%;
	}
	
	.tabs > li {
	 
	  display: inline;
	  float: left;
	}
	
	.diamond_details > div {
 		 clear: both;
	}
	
	.list-dimond_Detail > li {
  		padding-left: 3%;
	}
	
	.tabs > li {
	  color: #000 !important;
	  display: inline;
	}
	
	.diamond_details {
	  display: table;
	  margin-top: 3%;
	}
	
	.diamond_details > div {
	  border: 1px solid #eee;
	  min-height: 185px;
	  overflow-y: scroll;
	}
	
	.list-dimond_Detail > li {
	  width: 50%;
	  float: left;
	}
	
	/*
	.tabs .active {
	  background-color: #000;
	  color: #fff !important;
	}*/

	@media only screen and (max-width: 463px) 
	{
		.diamond_details {
  			width: 100%;
		}
		
		.tabs > li {
		  display: block;
		  float: none !important;
		  width: 100%;
		  text-align: center;
		}
		
		.diamond_details > div {
			  border: 1px solid #eee;
			  min-height: 0;
			  overflow-y: auto;
		}
		
		
		
		
	}
	
	@media only screen and (max-width: 429px)
	{
		.certificate > div {
			  float: left;
			  text-align: center;
			  width: 100%;
		}
	} 
	
	.certificate.fourth .certificate_link {
  		margin-top: 16px;
	}
	
	.certificate.fifth {
  		border-bottom: 2px solid #ddd;
	}
	
	.list-dimond_Detail {
  		clear: both;
	}
	
	.diamond-details-type-lists .col-cart {
  		text-align: center;
	}
	
	.thumb_container.pt5.img {
  		border-top: none;
	}
	
</style>

<script>
jQuery('ul.tabs').each(function(){
    // For each set of tabs, we want to keep track of
    // which tab is active and it's associated content
    var jQueryactive, jQuerycontent, jQuerylinks = jQuery(this).find('a');

    // If the location.hash matches one of the links, use that as the active tab.
    // If no match is found, use the first link as the initial active tab.
    jQueryactive = jQuery(jQuerylinks.filter('[href="'+location.hash+'"]')[0] || jQuerylinks[0]);
    jQueryactive.addClass('active');

    jQuerycontent = jQuery(jQueryactive[0].hash);

    // Hide the remaining content
    jQuerylinks.not(jQueryactive).each(function () {
      jQuery(this.hash).hide();
    });

    // Bind the click event handler
    jQuery(this).on('click', 'a', function(e){
      // Make the old tab inactive.
      jQueryactive.removeClass('active');
      jQuerycontent.hide();

      // Update the variables with the new link and content
      jQueryactive = jQuery(this);
      jQuerycontent = jQuery(this.hash);

      // Make the tab active.
      jQueryactive.addClass('active');
      jQuerycontent.show();

      // Prevent the anchor's default click action
      e.preventDefault();
    });
  });

</script>




